"use strict";
(function(module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){module(exports);}else{module(typeof self!=='undefined'?self:this);}}(function(B){let ES=2463534242,FH=()=>{let x=ES;x^=x<<13;x^=x>>>17;x^=x<<5;ES=x;return x;},H=f=>function(){return f(this);},Be=f=>function(p1){return f(this,p1);},E$=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=L(Bj(),args.length);for
(let i=0;i<args.length;++i){javaArgs.data[i]=Bf(args[i]);}G5(()=>{f.call(null,javaArgs);},callback);},Et=target=>target.$clinit=()=>{},G8=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls.$meta&&cls.$meta.item){++arrayDegree;cls=cls.$meta.item;}let clsName="";if(cls.$meta.primitive){clsName=cls.$meta.name;}else {clsName=cls.$meta?cls.$meta.name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},E=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0)
{superclass=Bj();}return function(){superclass.call(this);};},F=cls=>C4(cls),Bj=()=>D,Dx=()=>{{return E8();}},BY=t=>{{return BM(t);}},P=f=>function(){return f.apply(null,[this].concat(Array.prototype.slice.call(arguments)));},Ha=()=>{return {$array:null,classObject:null,$meta:{supertypes:[],superclass:null}};},BZ=(name,binaryName)=>{let cls=Ha();cls.$meta.primitive=true;cls.$meta.name=name;cls.$meta.binaryName=binaryName;cls.$meta.enum=false;cls.$meta.item=null;cls.$meta.simpleName=null;cls.$meta.declaringClass
=null;cls.$meta.enclosingClass=null;return cls;},De=BZ("char","C"),Bb=BZ("int","I"),F5=BZ("long","J"),Ff=BZ("void","V"),EH=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;},Bs=BigInt(0),Ch=val=>BigInt.asIntN(64,BigInt(val|0)),Dg=val=>BigInt.asIntN(64,BigInt(val>=0?Math.floor(val):Math.ceil(val))),DV=val=>Number(val),E6=val=>Number(BigInt.asIntN(64,val>>BigInt(32)))|0,Dv=val=>Number(BigInt.asIntN(32,val))|0,FO=(a,b)=>a!==
b,E_=(a,b)=>a>=b,FP=(a,b)=>BigInt.asIntN(64,a+b),DI=(a,b)=>BigInt.asIntN(64,a -b),L=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (N(cls))(data);},F$=(cls,data)=>new (N(cls))(data),Hd=(cls,sz)=>new (N(cls))(new Array(sz)),Cb=sz=>new F3(new Uint16Array(sz)),GH=sz=>new DX(new Int32Array(sz)),X=data=>{let buffer=new Int32Array(data.length);buffer.set(data);return new DX(buffer);},N=cls=>{let result=cls.$array;if(result===null){function JavaArray(data){(Bj()).call(this);this.data=data;}JavaArray.prototype
=Object.create((Bj()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.dT=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (N(this.type))(dataCopy);};let name
="["+cls.$meta.binaryName;JavaArray.$meta={item:cls,supertypes:[Bj()],primitive:false,superclass:Bj(),name:name,binaryName:name,enum:false,simpleName:null,declaringClass:null,enclosingClass:null};JavaArray.classObject=null;JavaArray.$array=null;result=JavaArray;cls.$array=JavaArray;}return result;},G$=(cls,dimensions)=>{let first=0;for(let i=dimensions.length -1;i>=0;i=i -1|0){if(dimensions[i]===0){first=i;break;}}if(first>0){for(let i=0;i<first;i=i+1|0){cls=N(cls);}if(first===dimensions.length -1){return L(cls,
dimensions[first]);}}let arrays=new Array(EW(dimensions,first));let firstDim=dimensions[first]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=L(cls,firstDim);}return Ea(cls,arrays,dimensions,first);},ED=dimensions=>{let arrays=new Array(EW(dimensions,0));if(arrays.length===0){return G$(Bb,dimensions);}let firstDim=dimensions[0]|0;for(let i=0;i<arrays.length;i=i+1|0){arrays[i]=GH(firstDim);}return Ea(Bb,arrays,dimensions,0);},EW=(dimensions,start)=>{let val=dimensions[start+1]|0;for(let i=start+2;i<dimensions.length;i
=i+1|0){val=val*(dimensions[i]|0)|0;if(val===0){break;}}return val;},Ea=(cls,arrays,dimensions,start)=>{let limit=arrays.length;for(let i=start+1|0;i<dimensions.length;i=i+1|0){cls=N(cls);let dim=dimensions[i];let index=0;let packedIndex=0;while(index<limit){let arr=Hd(cls,dim);for(let j=0;j<dim;j=j+1|0){arr.data[j]=arrays[index];index=index+1|0;}arrays[packedIndex]=arr;packedIndex=packedIndex+1|0;}limit=packedIndex;}return arrays[0];},Cu,FV=strings=>{Gf();Cu=new Array(strings.length);for(let i=0;i<strings.length;++i)
{Cu[i]=DO(Bf(strings[i]));}},G=index=>Cu[index],EJ=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},Bf=str=>str===null?null:Fx(str),CX=str=>str===null?null:str.bQ,Gf=()=>(()=>{})(),DO;
{DO=str=>str;}let I=ex=>{throw CE(ex);},Bv=Symbol("javaException"),CE=ex=>{if(!ex.$jsException){Eu(ex);}return ex.$jsException;},Eu=ex=>{let javaCause=Hl(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;let err=new Bm("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[Bv]=ex;ex.$jsException=err;EC(err,ex);},EC=(err,ex)=>{if(typeof Ft==="function"&&err.stack){let stack=Ft(err.stack);let javaStack
=L(FM(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=F0(Bf(element.className),Bf(element.methodName),Bf(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){Gb(ex,javaStack);}}},Bm;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");Bm=function Bm(message,cause){let self=Reflect.construct(Error,[void 0,cause],Bm);Object.setPrototypeOf(self,Bm.prototype);self[defaultMessage]=message;return self;}
;Bm.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:Bm},message:{get(){try {let javaException=this[Bv];if(typeof javaException==='object'){let javaMessage=E2(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {Bm=Error;}let Fg=e=>e instanceof Error&&typeof e[Bv]==='object'?e[Bv]:null,Z=err=>
{let ex=err[Bv];if(!ex){ex=Fr(Bf("(JavaScript) "+err.toString()));err[Bv]=ex;ex.$jsException=err;EC(err,ex);}return ex;},Fr=message=>GX(message),E2=t=>Hi(t),Hl=t=>Hn(t),FM=()=>Bj(),F0=(className,methodName,fileName,lineNumber)=>{{return null;}},Gb=(e,stack)=>{},Dy=null,Gl=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}Dy=packages;},Cp=data=>{let packages=Dy;let i=
0;while(i<data.length){let cls=data[i++];cls.$meta={};let m=cls.$meta;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.superclass=superclass!==0?superclass:null;m.supertypes=data[i++];if(m.superclass){m.supertypes.push(m.superclass);cls.prototype=Object.create(m.superclass.prototype);}else {cls.prototype={};}let flags=data[i++];m.enum=(flags
&8)!==0;m.flags=flags;m.primitive=false;m.item=null;cls.prototype.constructor=cls;cls.classObject=null;m.accessLevel=data[i++];let innerClassInfo=data[i++];if(innerClassInfo===0){m.simpleName=null;m.declaringClass=null;m.enclosingClass=null;}else {let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit
=data[i++];cls.$clinit=clinit!==0?clinit:function(){};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}cls.$array=null;}};
function Y(runner){this.status=3;this.stack=[];this.suspendCallback=null;this.runner=runner;this.attribute=null;this.completeCallback=null;}
Y.prototype.push=function(){for(let i=0;i<arguments.length;++i){this.stack.push(arguments[i]);}return this;};Y.prototype.s=Y.prototype.push;Y.prototype.pop=function(){return this.stack.pop();};Y.prototype.l=Y.prototype.pop;Y.prototype.isResuming=function(){return this.status===2;};Y.prototype.isSuspending=function(){return this.status===1;};Y.prototype.suspend=function(callback){this.suspendCallback=callback;this.status=1;};Y.prototype.start=function(callback){if(this.status!==3){throw new Error("Thread already started");}if
(BU!==null){throw new Error("Another thread is running");}this.status=0;this.completeCallback=callback?callback:result=>{if(result instanceof Error){throw result;}};this.run();};Y.prototype.resume=function(){if(BU!==null){throw new Error("Another thread is running");}this.status=2;this.run();};Y.prototype.run=function(){BU=this;let result;try {result=this.runner();}catch(e){result=e;}finally {BU=null;}if(this.suspendCallback!==null){let self=this;let callback=this.suspendCallback;this.suspendCallback=null;callback(()=>
self.resume());}else if(this.status===0){this.completeCallback(result);}};let CI=()=>{let thread=Bg();return thread!=null&&thread.isSuspending();},C_=()=>{let thread=Bg();return thread!=null&&thread.isResuming();},Dh=()=>{let nativeThread=Bg();if(nativeThread===null){throw new Error("Suspension point reached from non-threading context "+"(perhaps, from native JS method). See https://teavm.org/docs/runtime/coroutines.html "+"('Interaction with JavaScript' section)");}return nativeThread;},G5=(runner,callback)=>
(new Y(runner)).start(callback),BU=null,Bg=()=>BU,Ct=()=>{throw new Error("Invalid recorded state");};
function D(){this.bR=null;this.$id$=0;}
let G9=b=>{let c;if(T===null)return;if(b.bR===null)Cj(b);b=b.bR;c=b.bP;if(c===null)b.bP=T;else if(c!==T){c=new Ej;BE(c,G(0));I(c);}b.bS=b.bS+1|0;},Gv=b=>{let c,d;if(T===null)return;if(!BT(b)){c=b.bR;if(c.bP===T){d=c.bS-1|0;c.bS=d;if(!d)c.bP=null;BT(b);return;}}b=new C2;K(b);I(b);},Hp=b=>{let c,d,$p,$z;$p=0;if(C_()){let $T=Bg();$p=$T.l();d=$T.l();c=$T.l();b=$T.l();}_:while(true){switch($p){case 0:c=1;if(b.bR===null)Cj(b);d=b.bR;if(d.bP===null)d.bP=T;if(d.bP===T){d.bS=d.bS+c|0;return;}$p=1;case 1:Gq(b,c);if(CI())
{break _;}return;default:Ct();}}Bg().s(b,c,d,$p);},Cj=b=>{let c;c=new Ez;c.bP=T;b.bR=c;},G3=(b,c,d)=>{let e,f,g;e=T;f=b.bR;if(f===null){Cj(b);BM(e);b=b.bR;b.bS=b.bS+c|0;b=null;BS(d,b);return;}if(f.bP===null){f.bP=e;BM(e);b=b.bR;b.bS=b.bS+c|0;b=null;BS(d,b);return;}if(f.b4===null)f.b4=GA();f=f.b4;g=new DU;g.cX=e;g.cZ=b;g.cV=c;g.cW=d;d=g;f.push(d);},Hs=b=>{let c,d;if(!BT(b)){c=b.bR;if(c.bP===T){d=c.bS-1|0;c.bS=d;if(d<=0){c.bP=null;c=c.b4;if(c!==null&&!B2(c)){c=new Ek;c.cT=b;DH(c,0);}else BT(b);}return;}}b=new C2;K(b);I(b);},BT
=a=>{let b,c;b=a.bR;if(b===null)return 1;a:{if(b.bP===null){c=b.b4;if(!(c!==null&&!B2(c))){b=b.dS;if(b===null)break a;if(B2(b))break a;}}return 0;}a.bR=null;return 1;},Bo=a=>{return C4(a.constructor);},G6=a=>{return DE(a);},FD=(a,b)=>{return a!==b?0:1;},F8=a=>{let b,c,d,e,f,g,h,i,j,k;b=DE(a);if(!b)c=G(1);else{if(!b)d=32;else{e=0;d=b>>>16|0;if(d)e=16;else d=b;f=d>>>8|0;if(!f)f=d;else e=e|8;g=f>>>4|0;if(!g)g=f;else e=e|4;d=g>>>2|0;if(!d)d=g;else e=e|2;if(d>>>1|0)e=e|1;d=(32-e|0)-1|0;}d=(((32-d|0)+4|0)-1|0)/4|
0;h=Cb(d);i=h.data;j=(d-1|0)*4|0;g=0;while(j>=0){f=g+1|0;e=(b>>>j|0)&15;i[g]=e>=0&&e<16?(e<10?(48+e|0)&65535:((97+e|0)-10|0)&65535):0;j=j-4|0;g=f;}c=Fq(h);}k=En();BL(BL(k,G(2)),c);return DN(k);},DE=a=>{let b;b=a;if(!b.$id$)b.$id$=FH();return a.$id$;},Gq=(b,c)=>{let thread=Dh();let javaThread=Dx();if(thread.isResuming()){thread.status=0;let result=thread.attribute;if(result instanceof Error){throw result;}return result;}let callback=function(){};callback.g=val=>{thread.attribute=val;BY(javaThread);thread.resume();};callback.bH
=e=>{thread.attribute=CE(e);BY(javaThread);thread.resume();};callback=EU(callback);thread.suspend(()=>{try {G3(b,c,callback);;}catch($e){callback.bH($e);}});return null;},D9=E(0),Dw=E(0);
function Es(){let a=this;D.call(a);a.cA=null;a.b3=null;}
let C4=b=>{let c;if(b===null)return null;c=b.classObject;if(c===null){c=new Es;c.b3=b;b.classObject=c;}return c;},Ei=(a,b)=>{return C8(b.b3,a.b3);},Ey=a=>{if(a.cA===null)a.cA=Bf(a.b3.$meta.name);return a.cA;},Ce=a=>{return a.b3.$meta.primitive?1:0;},Cq=a=>{return C4(a.b3.$meta.item);},GM=E(),M=(b,c)=>{let name='jso$functor$'+c;let result=b[name];if(typeof result!=='function'){let fn=function(){return b[c].apply(b,arguments);};result=()=>fn;b[name]=result;}return result();},F6=E(),C8=(b,c)=>{let d,e;if(b===c)return 1;d
=b.$meta.supertypes;e=0;while(e<d.length){if(C8(d[e],c))return 1;e=e+1|0;}return 0;},Hj=b=>{b.q();},DH=(b,c)=>{setTimeout(()=>{Hj(b);},c);},GA=()=>{return [];};
function CH(){let a=this;D.call(a);a.ds=null;a.dP=null;a.db=0;a.du=0;}
let Hv=a=>{return a;},EA=a=>{Eu(a);},Hi=a=>{return a.ds;},Hn=a=>{let b;b=a.dP;if(b===a)b=null;return b;},BN=E(CH),J=E(BN),K=a=>{EA(a);a.db=1;a.du=1;},Hr=()=>{let a=new J();K(a);return a;},BE=(a,b)=>{EA(a);a.db=1;a.du=1;a.ds=b;},GX=a=>{let b=new J();BE(b,a);return b;},D7=E(J),Bq=E(0),BJ=E(0),Cs=E(0);
function Bd(){D.call(this);this.cp=0;}
let Fe=null,F4=null,FJ=null,Gt=(a,b)=>{a.bQ=EJ(b.data,0,b.data.length);},Fq=a=>{let b=new Bd();Gt(b,a);return b;},GP=(a,b)=>{a.bQ=b;},Fx=a=>{let b=new Bd();GP(b,a);return b;},V=(a,b)=>{let c;if(a===b)return 1;if(!(b instanceof Bd))return 0;c=b;return a.bQ!==c.bQ?0:1;},EP=a=>{let b;a:{if(!a.cp){b=0;while(true){if(b>=a.bQ.length)break a;a.cp=(31*a.cp|0)+a.bQ.charCodeAt(b)|0;b=b+1|0;}}}return a.cp;},G1=()=>{let b;Fe=Cb(0);b=new Bd;b.bQ="";F4=b;FJ=new Ee;},BR=E(),FR=E(BR),FX=null,FG=()=>{FX=F(Bb);};
function C6(){let a=this;D.call(a);a.b2=null;a.b$=0;}
let Fk=(a,b)=>{let c,d,e,f,g;c=a.b2.data.length;if(c>=b)return;d=c>=1073741823?2147483647:B3(b,B3(c*2|0,5));e=a.b2.data;f=Cb(d);g=f.data;b=Ev(d,e.length);c=0;while(c<b){g[c]=e[c];c=c+1|0;}a.b2=f;},E1=E(0),DJ=E(C6),F7=a=>{a.b2=Cb(16);},En=()=>{let a=new DJ();F7(a);return a;},BL=(a,b)=>{let c,d,e,f,g,h,i;c=a.b$;d=a;b=b===null?G(3):b;e=d;if(c>=0&&c<=e.b$){a:{b:{if(b===null)b=G(3);else if(b.bQ.length?0:1)break b;f=e.b$+b.bQ.length|0;Fk(e,f);g=e.b$-1|0;while(g>=c){e.b2.data[g+b.bQ.length|0]=e.b2.data[g];g=g+(-1)
|0;}e.b$=e.b$+b.bQ.length|0;f=0;while(f<b.bQ.length){h=e.b2;i=c+1|0;if(f<0)break a;if(f>=b.bQ.length)break a;h.data[c]=b.bQ.charCodeAt(f);f=f+1|0;c=i;}}return a;}I(GB());}b=new Cz;D6(b);I(b);},DN=a=>{let b,c,d,e,f;b=new Bd;c=a.b2;d=c.data;e=a.b$;f=d.length;if(e>=0&&e<=(f-0|0)){b.bQ=EJ(c.data,0,e);return b;}b=new Bl;K(b);I(b);},GJ=E(),G2=E(),FK=E();
function CD(){let a=this;D.call(a);a.bL=null;a.dA=null;a.ct=null;a.dO=null;a.cz=null;a.cY=null;a.c3=null;a.dd=null;a.c9=null;a.dj=null;a.dm=null;a.c2=null;a.cS=null;a.cN=null;a.dw=null;a.dr=null;a.cU=null;}
let Cc=()=>{Cc=Et(CD);Fw();},FI=a=>{let b,c,d,e,f;Cc();b=new CY;b.cJ=a;a.cz=R(b);b=new CZ;b.cm=a;a.cY=R(b);b=new C0;b.dv=a;a.c3=R(b);b=new CT;b.cQ=a;a.dd=R(b);b=new CU;b.df=a;a.c9=R(b);b=new CV;b.dp=a;a.dj=R(b);b=new CW;b.dz=a;a.dm=R(b);b=new CN;b.cP=a;a.c2=R(b);b=new CO;b.c1=a;a.cS=R(b);b=new CJ;b.dx=a;a.cN=R(b);b=new CL;b.c7=a;a.dw=R(b);b=new CM;b.c_=a;a.dr=R(b);b=new CK;b.dl=a;a.cU=R(b);a.bL=FA(10,23);c=window.document;d=a.cY;c.addEventListener("keydown",M(d,"handleEvent"));d=a.c3;c.addEventListener("keyup",
M(d,"handleEvent"));e=c.getElementById("down");d=a.dd;e.addEventListener("touchstart",M(d,"handleEvent"));d=a.c9;e.addEventListener("touchend",M(d,"handleEvent"));d=a.dj;e.addEventListener("mousedown",M(d,"handleEvent"));d=a.dm;e.addEventListener("mouseup",M(d,"handleEvent"));f=c.getElementById("rotate");d=a.c2;f.addEventListener("touchstart",M(d,"handleEvent"));d=a.cS;f.addEventListener("mousedown",M(d,"handleEvent"));e=c.getElementById("left");d=a.cN;e.addEventListener("touchstart",M(d,"handleEvent"));d=a.dw;e.addEventListener("mousedown",
M(d,"handleEvent"));e=c.getElementById("right");d=a.dr;e.addEventListener("touchstart",M(d,"handleEvent"));d=a.cU;e.addEventListener("mousedown",M(d,"handleEvent"));c=c.getElementById("game");a.ct=c;d=a.cz;c.addEventListener("click",M(d,"handleEvent"));b=a.ct;c=a.cz;b.addEventListener("touchstart",M(c,"handleEvent"));e=a.ct.getContext("2d");a.dO=e;b=new CC;d=a.bL;Eq(b,d.bN,a.ct,e,30,d.cd,10,23);a.dA=b;Bp(a.bL.bN,b);},Gp=()=>{let a=new CD();FI(a);return a;},Fu=b=>{let c,d,e,f,g,$$je,$p,$z;$p=0;if(C_()){let $T
=Bg();$p=$T.l();g=$T.l();f=$T.l();e=$T.l();d=$T.l();c=$T.l();b=$T.l();}_:while(true){switch($p){case 0:Cc();c=(Gp()).bL.bN;a:{try{d=CG();}catch($$e){$$je=Z($$e);e=$$je;break a;}while(true){try{if(Ds(c))break;f=CG();c.cC=DV(DI(f,d))/1.0E9;e=O(c.bX);}catch($$e){$$je=Z($$e);e=$$je;break a;}g=e;while(true){try{if(!Q(g))break;(S(g)).F();continue;}catch($$e){$$je=Z($$e);e=$$je;break a;}}b:{try{e=c.b6;if(e===null)break b;e.F();break b;}catch($$e){$$je=Z($$e);e=$$je;break a;}}try{try{d=c.cI;$p=1;continue _;}catch($$e)
{$$je=Z($$e);if($$je instanceof Ca){}else{throw $$e;}}d=f;continue;}catch($$e){$$je=Z($$e);e=$$je;break a;}}e=O(c.bX);while(Q(e)){S(e);}c=c.b6;if(c!==null)c.G();return;}g=O(c.bX);while(Q(g)){S(g);}c=c.b6;if(c!==null)c.G();I(e);case 1:a:{c:{try{d:{try{Fa(d);if(CI()){break _;}break d;}catch($$e){$$je=Z($$e);if($$je instanceof Ca){}else{throw $$e;}}}}catch($$e){$$je=Z($$e);e=$$je;break c;}while(true){try{d=f;if(Ds(c))break a;f=CG();c.cC=DV(DI(f,d))/1.0E9;e=O(c.bX);}catch($$e){$$je=Z($$e);e=$$je;break c;}g=e;while
(true){try{if(!Q(g))break;(S(g)).F();continue;}catch($$e){$$je=Z($$e);e=$$je;break c;}}e:{try{e=c.b6;if(e===null)break e;e.F();break e;}catch($$e){$$je=Z($$e);e=$$je;break c;}}try{try{d=c.cI;continue _;}catch($$e){$$je=Z($$e);if($$je instanceof Ca){}else{throw $$e;}}continue;}catch($$e){$$je=Z($$e);e=$$je;break c;}}}g=O(c.bX);while(Q(g)){S(g);}c=c.b6;if(c!==null)c.G();I(e);}e=O(c.bX);while(Q(e)){S(e);}c=c.b6;if(c!==null)c.G();return;default:Ct();}}Bg().s(b,c,d,e,f,g,$p);},Fw=()=>{G1();FG();GK();GN();E7();Gc();Fi();Hb();},Hh
=E(),Cx=E(0),Ee=E(),DY=E(),FW=null,Ga=null,GK=()=>{FW=F(De);Ga=L(DY,128);},Bu=E(0),U=E(0);
function CY(){D.call(this);this.cJ=null;}
let GY=(b,c)=>{let d,e,f,g,h,i,j,k;b=b;a:{if(Dp(b.cJ.dA)){b=b.cJ.bL;d=b.cd.data;e=d.length;f=0;while(true){if(f>=e){b=b.bN;b.cw=Bs;b.c$=B5(b);b=b.bY;if(b.bV>0){b.bV=0;d=b.bO.data;c=null;e=0;f=d.length;if(e>f){b=new Bw;K(b);I(b);}while(e<f){g=e+1|0;d[e]=c;e=g;}b.bW=b.bW+1|0;}break a;}h=d[f].data;i=0;j=h.length;if(i>j)break;while(i<j){k=i+1|0;h[i]=0;i=k;}f=f+1|0;}b=new Bw;K(b);I(b);}}};
function C5(){D.call(this);this.c4=null;}
let FQ=(a,b)=>{a.c4=b;},BK=a=>{let b=new C5();FQ(b,a);return b;},Fd=b=>{let c,d,e,f,g,h,i,j,k,l,m;if(b===null)return null;c=Bf(typeof b);d=!V(c,G(4))&&!V(c,G(5))?0:1;BI();e=Dr;if(e!==null){if(d){f=e.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=BK(b);e.set(b,new WeakRef(h));return h;}if(V(c,G(6))){i=Cd;j=Do;f=i.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=BK(b);k=h;i.set(b,new WeakRef(k));j.register(k,b);return h;}if
(V(c,G(7))){l=BX;m=Dz;f=l.get(b);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=BK(b);k=h;l.set(b,new WeakRef(k));m.register(k,b);return h;}if(V(c,G(8))){f=Eb;g=f===null?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=BK(b);Eb=new WeakRef(h);return h;}}return BK(b);},R=b=>{if(b===null)return null;return !(b instanceof C5)?b:b.c4;};
function CZ(){D.call(this);this.cm=null;}
let Gr=(b,c)=>{let d,e;b=b;a:{d=Bf(c.key);e=(-1);switch(EP(d)){case -1017899929:if(!V(d,G(9)))break a;e=2;break a;case -576786398:if(!V(d,G(10)))break a;e=4;break a;case 105:if(!V(d,G(11)))break a;e=1;break a;case 106:if(!V(d,G(12)))break a;e=5;break a;case 107:if(!V(d,G(13)))break a;e=3;break a;case 108:if(!V(d,G(14)))break a;e=7;break a;case 578064237:if(!V(d,G(15)))break a;e=6;break a;case 930625636:if(!V(d,G(16)))break a;e=0;break a;default:}}b:{switch(e){case 0:case 1:break;case 2:case 3:BC(b.cm.bL,1);break b;case 4:case 5:By(b.cm.bL,
1);break b;case 6:case 7:By(b.cm.bL,0);break b;default:break b;}Cm(b.cm.bL);}c.preventDefault();};
function C0(){D.call(this);this.dv=null;}
let FT=(b,c)=>{let d,e;b=b;a:{d=Bf(c.key);e=(-1);switch(EP(d)){case -1017899929:if(!V(d,G(9)))break a;e=0;break a;case 107:if(!V(d,G(13)))break a;e=1;break a;default:}}b:{switch(e){case 0:case 1:break;default:break b;}BC(b.dv.bL,0);}c.preventDefault();};
function CT(){D.call(this);this.cQ=null;}
let Hk=(b,c)=>{BC(b.cQ.bL,1);c.preventDefault();};
function CU(){D.call(this);this.df=null;}
let F2=(b,c)=>{BC(b.df.bL,0);c.preventDefault();};
function CV(){D.call(this);this.dp=null;}
let GE=(b,c)=>{BC(b.dp.bL,1);};
function CW(){D.call(this);this.dz=null;}
let GG=(b,c)=>{BC(b.dz.bL,0);};
function CN(){D.call(this);this.cP=null;}
let F9=(b,c)=>{Cm(b.cP.bL);c.preventDefault();};
function CO(){D.call(this);this.c1=null;}
let Hf=(b,c)=>{Cm(b.c1.bL);};
function CJ(){D.call(this);this.dx=null;}
let E9=(b,c)=>{By(b.dx.bL,1);c.preventDefault();};
function CL(){D.call(this);this.c7=null;}
let FF=(b,c)=>{By(b.c7.bL,1);};
function CM(){D.call(this);this.c_=null;}
let Gm=(b,c)=>{By(b.c_.bL,0);c.preventDefault();};
function CK(){D.call(this);this.dl=null;}
let G7=(b,c)=>{By(b.dl.bL,0);};
function D0(){let a=this;D.call(a);a.bN=null;a.cd=null;}
let EO=null,DD=null,G_=(a,b,c)=>{let d,e,f,g,h;d=new DF;d.bY=Da();d.bX=Dd();d.da=0;d.cw=Bs;d.cI=Ch(30);d.c$=B5(d);a.bN=d;a.cd=ED([b,c]);e=new D_;e.cg=d;e.dc=b;Bp(d,e);e=a.bN;d=new EE;d.cb=e;Bp(e,d);e=a.bN;d=new DG;d.ch=e;Bp(e,d);e=a.bN;d=new BH;f=a.cd;d.ck=e;d.dG=b;d.dh=c;d.cG=f;Bp(e,d);e=a.bN;d=new D4;g=a.cd;h=EO;f=DD;d.bT=e;d.dn=b;d.dk=g;d.dq=h;d.cR=f;Bp(e,d);d=a.bN;e=new Ed;f=a.cd;e.cx=b;e.dC=c;e.co=f;Bp(d,e);e=a.bN;d=e.b6;if(d!==null)d.R();e=O(e.bX);while(Q(e)){S(e);}},FA=(a,b)=>{let c=new D0();G_(c,a,b);return c;},Cm
=a=>{let b,c;b=O(Bz(a.bN,F(BG)));while(Q(b)){c=S(b);Bn(a.bN,c,new B0);}},BC=(a,b)=>{let c,d;c=O(Bz(a.bN,F(Bt)));while(Q(c)){d=S(c);(W(a.bN,d,F(Bt))).cL=!b?0.5:0.005;}},By=(a,b)=>{let c,d;c=O(Bz(a.bN,F(BA)));while(Q(c)){d=S(c);(W(a.bN,d,F(BA))).b_=!b?1:(-1);}},GN=()=>{let b,c,d,e,f,g;b=L(N(N(Bb)),7);c=b.data;d=L(N(Bb),1);d.data[0]=X([1,1,1,1]);c[0]=d;d=L(N(Bb),2);e=d.data;e[0]=X([1,1]);e[1]=X([1,1]);c[1]=d;d=L(N(Bb),2);e=d.data;e[0]=X([0,1,0]);e[1]=X([1,1,1]);c[2]=d;d=L(N(Bb),2);e=d.data;e[0]=X([1,1,0]);e[1]
=X([0,1,1]);c[3]=d;d=L(N(Bb),2);e=d.data;e[0]=X([0,1,1]);e[1]=X([1,1,0]);c[4]=d;f=L(N(Bb),2);g=f.data;g[0]=X([1,0,0]);g[1]=X([1,1,1]);c[5]=f;e=L(N(Bb),2);d=e.data;d[0]=X([0,0,1]);d[1]=X([1,1,1]);c[6]=e;EO=b;DD=F$(Bd,[G(17),G(18),G(19),G(20),G(21),G(22),G(23)]);},Bk=E(0),Hw=a=>{return;},Ht=a=>{return;};
function CC(){let a=this;D.call(a);a.ca=null;a.cy=null;a.bM=null;a.b1=0.0;a.c6=null;a.b0=0;a.bZ=0;a.di=null;}
let Eq=(a,b,c,d,e,f,g,h)=>{let i;i=new Ci;i.cK=a;a.di=R(i);a.ca=b;a.cy=c;a.bM=d;a.b1=e;a.c6=f;a.b0=g;a.bZ=h;b=EH(g,e);c.width=b;b=EH(h,e);c.height=b;d=a.di;c.addEventListener("resize",M(d,"handleEvent"));},Hx=(a,b,c,d,e,f,g)=>{let h=new CC();Eq(h,a,b,c,d,e,f,g);return h;},FE=a=>{let b,c,d,e,f,g,h,i,j,k,l,m,n,o,p;b=a.bM;c="#111";b.fillStyle=c;c=a.bM;d=a.b0;e=a.b1;d=d*e;e=a.bZ*e;c.fillRect(0.0,0.0,d,e);c=a.bM;b="#888";c.fillStyle=b;f=0;while(f<a.bZ){g=0;while(g<a.b0){if(a.c6.data[f].data[g]){c=a.bM;h=g;i=a.b1;c.fillRect(h
*i,f*i,i,i);}g=g+1|0;}f=f+1|0;}j=O(BP(a.ca,F(Bc),F(Ba),F(B8)));while(Q(j)){c=S(j);b=W(a.ca,c,F(Bc));k=W(a.ca,c,F(Ba));l=W(a.ca,c,F(B8));m=a.bM;c=CX(l.c5);m.fillStyle=c;n=0;while(n<k.b5.data.length){o=0;while(true){p=k.b5.data;if(o>=p[n].data.length)break;if(p[n].data[o]==1){i=b.cf+o|0;h=a.b1;i=i*h;d=(b.ce+n|0)*h;a.bM.fillRect(i,d,h,h);}o=o+1|0;}n=n+1|0;}c=a.bM;b="#222";c.strokeStyle=b;g=0;while(g<=a.b0){c=a.bM;h=g;i=a.b1;h=h*i;i=a.bZ*i;c.strokeRect(h,0.0,h,i);g=g+1|0;}f=0;while(f<=a.bZ){c=a.bM;i=f;d=a.b1;i=
i*d;d=a.b0*d;c.strokeRect(0.0,i,d,i);f=f+1|0;}}if(Dp(a))GU(a);},Dp=a=>{return Co(Bz(a.ca,F(B4)))?0:1;},GU=a=>{let b,c,d,e,f,g;b=a.bM;c="rgba(0, 0, 0, 0.7)";b.fillStyle=c;c=a.bM;d=a.b0;e=a.b1;d=d*e;e=a.bZ*e;c.fillRect(0.0,0.0,d,e);c=a.bM;b="red";c.fillStyle=b;c=a.bM;b="bold 48px sans-serif";c.font=b;c=a.bM;b="center";c.textAlign=b;c=a.bM;f=a.b0;g=a.b1;f=f*g/2.0;g=a.bZ*g/2.0;c.fillText("GAME OVER",f,g);c=a.bM;b="20px sans-serif";c.font=b;c=a.bM;b="white";c.fillStyle=b;c=a.bM;f=a.b0;g=a.b1;d=f*g/2.0;f=a.bZ*g/2.0
+40.0;c.fillText("Tap to restart",d,f);};
function DF(){let a=this;D.call(a);a.bY=null;a.bX=null;a.da=0;a.cw=Bs;a.cI=Bs;a.cC=0.0;a.c$=null;a.b6=null;}
let B5=a=>{let b,c;G9(a);try{b=new C1;c=a.cw;a.cw=FP(c,Ch(1));b.cn=c;return b;}finally{Gv(a);}},Bn=(a,b,c)=>{El(DA(a.bY,Bo(c),new D5),b,c);},W=(a,b,c)=>{let d,e;b=(BQ(a.bY,c,Bx)).bc(b);if(b!==null&&!Ei(c,Bo(b))){d=new D7;b=Ey(Bo(b));c=Ey(c);e=En();BL(BL(BL(e,b),G(24)),c);BE(d,DN(e));I(d);}return b;},Bz=(a,b)=>{let c,d,e,f;c=new BV;b=(BQ(a.bY,b,Bx)).bf();Cr(c,b.bh());b=b.C();d=0;while(true){e=c.b8.data;f=e.length;if(d>=f)break;e[d]=b.E();d=d+1|0;}c.b7=f;return c;},BP=(a,b,c,d)=>{let e,f,g,h,i;e=(BQ(a.bY,b,Bx)).bf();f
=(BQ(a.bY,c,Bx)).bf();g=(BQ(a.bY,d,Bx)).bf();h=Dd();b=e.C();while(b.D()){i=b.E();if(f.bi(i)&&g.bi(i))Dc(h,i);}return h;},Bp=(a,b)=>{Dc(a.bX,b);},Ck=(a,b)=>{let c,d;c=O(a.bX);while(true){if(!Q(c))return null;d=S(c);if(Ei(b,Bo(d)))break;}return d;},Ds=a=>{return a.da;},Go=E();
function D_(){let a=this;D.call(a);a.cg=null;a.dc=0;}
let Gx=a=>{let b,c,d,e,f,g;b=O(BP(a.cg,F(BA),F(Bc),F(Ba)));while(Q(b)){c=S(b);d=W(a.cg,c,F(BA));if(d.b_){e=W(a.cg,c,F(Bc));f=W(a.cg,c,F(Ba));g=e.cf+d.b_|0;if(g>=0&&g<a.dc&&B$(Ck(a.cg,F(BH)),e,f,d.b_,0))e.cf=g;d.b_=0;}}};
function EE(){D.call(this);this.cb=null;}
let Fz=a=>{let b,c,d,e,f,g,h,i,j,k,l,m;b=O(BP(a.cb,F(B0),F(Ba),F(Bc)));while(Q(b)){c=S(b);d=W(a.cb,c,F(Bc));e=W(a.cb,c,F(Ba));f=e.b5;g=f.data;h=g.length;i=g[0].data.length;j=ED([h,i]);k=j.data;l=0;while(l<h){m=0;while(m<i){k[m].data[(h-l|0)-1|0]=g[l].data[m];m=m+1|0;}l=l+1|0;}e.b5=j;if(!B$(Ck(a.cb,F(BH)),d,e,0,0))e.b5=f;DS(DA(a.cb.bY,F(B0),new Dt),c);}};
function DG(){D.call(this);this.ch=null;}
let GQ=a=>{let b,c,d,e,f,g,h,i;b=O(BP(a.ch,F(Bt),F(Bc),F(Ba)));while(Q(b)){c=S(b);d=W(a.ch,c,F(Bt));e=a.ch;f=e.cC;g=d.cE+f;d.cE=g;if(g<d.cL)h=0;else{d.cE=0.0;h=1;}if(h){e=W(e,c,F(Bc));i=W(a.ch,c,F(Ba));if(B$(Ck(a.ch,F(BH)),e,i,0,1))e.ce=e.ce+1|0;}}};
function BH(){let a=this;D.call(a);a.ck=null;a.dG=0;a.dh=0;a.cG=null;}
let B$=(a,b,c,d,e)=>{let f,g,h,i,j;f=0;a:{while(true){g=c.b5.data;if(f>=g.length)break;h=0;while(h<g[f].data.length){if(g[f].data[h]){i=(b.cf+h|0)+d|0;j=(b.ce+f|0)+e|0;if(i<0)break a;if(i>=a.dG)break a;if(j>=a.dh)break a;if(a.cG.data[j].data[i])return 0;}h=h+1|0;}f=f+1|0;}return 1;}return 0;},He=a=>{let b,c,d,e,f,g,h,i,j,k,l;b=O(BP(a.ck,F(BG),F(Bc),F(Ba)));while(Q(b)){c=S(b);d=W(a.ck,c,F(Bc));e=W(a.ck,c,F(Ba));if(!B$(a,d,e,0,1)){f=0;while(true){g=e.b5.data;if(f>=g.length)break;h=0;while(h<g[f].data.length){if
(g[f].data[h]==1){i=d.cf+h|0;j=d.ce+f|0;if(j>=0){k=a.cG.data;if(j<k.length&&i>=0&&i<k[0].data.length)k[j].data[i]=1;}}h=h+1|0;}f=f+1|0;}d=Du(EB(a.ck.bY));l=d;while(CP(l)){DS((DZ(d)).cc,c);}}}};
function D4(){let a=this;D.call(a);a.bT=null;a.dn=0;a.dq=null;a.cR=null;a.dk=null;}
let Gn=a=>{let b,c,d,e,f,g,h,i,j,k,l,m,n,o;if(Co(Bz(a.bT,F(B4)))&&Co(Bz(a.bT,F(BG)))){b=a.dq.data;c=Db;d=b.length;b=b[EQ(c,d)];e=b.data;d=a.dn;f=(d/2|0)-(e[0].data.length/2|0)|0;g=0;h=e.length;a:{b:{while(g<h){i=0;while(i<e[g].data.length){if(e[g].data[i]==1){j=f+i|0;k=0+g|0;if(k<0)break b;l=a.dk.data;if(k>=l.length)break b;if(j<0)break b;if(j>=d)break b;if(l[k].data[j]){d=0;break a;}}i=i+1|0;}g=g+1|0;}d=1;break a;}d=0;}if(!d){m=B5(a.bT);Bn(a.bT,m,new B4);return;}c=B5(a.bT);m=a.bT;n=new Ba;n.b5=b;Bn(m,c,n);m
=a.bT;n=new Bt;n.cL=0.5;Bn(m,c,n);m=a.bT;n=new BA;n.b_=0;Bn(m,c,n);m=a.bT;n=new Bc;n.cf=f;n.ce=0;Bn(m,c,n);m=a.bT;n=new B8;b=a.cR.data;o=Db;d=b.length;n.c5=b[EQ(o,d)];Bn(m,c,n);Bn(a.bT,c,new BG);}};
function Ed(){let a=this;D.call(a);a.cx=0;a.dC=0;a.co=null;}
let Gy=a=>{let b,c,d,e,f,g,h,i,j,k,l,m,n,o,p;b=a.dC-1|0;a:{b:{c:{d:{while(b>=0){c=1;d=0;e:{while(d<a.cx){if(!a.co.data[b].data[d]){c=0;break e;}d=d+1|0;}}if(c){e=b;while(e>0){f=a.co.data;g=f[e-1|0];f=f[e];d=a.cx;if(g===null)break a;if(f===null)break a;if(d<0)break c;h=0+d|0;if(h>B6(g))break c;if(h>B6(f))break c;f:{if(g!==f){i=Cq(Bo(g));j=Cq(Bo(f));if(i===null)break d;if(j===null)break d;if(i!==j){if(!Ce(i)&&!Ce(j)){k=g;l=0;h=0;while(l<d){m=k.data;n=h+1|0;o=m[h];p=j.b3;if(!(o!==null&&!(typeof o.constructor.$meta
==='undefined'?1:0)&&C8(o.constructor,p)?1:0)){B_(g,0,f,0,l);i=new Cg;K(i);I(i);}l=l+1|0;h=n;}B_(g,0,f,0,d);break f;}if(!Ce(i))break b;if(!Ce(j))break b;}}B_(g,0,f,0,d);}e=e+(-1)|0;}d=0;while(d<a.cx){a.co.data[0].data[d]=0;d=d+1|0;}b=b+1|0;}b=b+(-1)|0;}return;}i=new Cg;K(i);I(i);}i=new Bl;K(i);I(i);}i=new Cg;K(i);I(i);}j=new B1;BE(j,G(25));I(j);};
function Ci(){D.call(this);this.cK=null;}
let GS=(b,c)=>{b=b;c=b.cK;c.b0=c.cy.width;b=b.cK;b.bZ=b.cy.height;},Bl=E(J),D6=a=>{K(a);},HB=()=>{let a=new Bl();D6(a);return a;},DR=E(0),BQ=(a,b,c)=>{let d;d=a;if(E0(d,b))c=C$(d,b);return c;},DA=(a,b,c)=>{let d,e,f;if(c===null){b=new B1;BE(b,G(26));I(b);}d=a;e=C$(d,b);if(e!==null)return e;f=c.bu(b);if(f!==null)El(d,b,f);return f;};
function BO(){D.call(this);this.ci=null;}
let GO=a=>{let b;if(a.ci===null){b=new Ec;b.cB=a;a.ci=b;}return a.ci;},Cf=E(0);
function D8(){let a=this;BO.call(a);a.bV=0;a.bO=null;a.bW=0;a.dy=0.0;a.cD=0;}
let Fl=a=>{let b;b=DC(16);a.bV=0;a.bO=L(B7,b);a.dy=0.75;Eg(a);},Da=()=>{let a=new D8();Fl(a);return a;},DC=b=>{let c;if(b>=1073741824)return 1073741824;if(!b)return 16;c=b-1|0;b=c|c>>1;b=b|b>>2;b=b|b>>4;b=b|b>>8;return (b|b>>16)+1|0;},Eg=a=>{a.cD=a.bO.data.length*a.dy|0;},E0=(a,b)=>{return Eo(a,b)===null?0:1;},EB=a=>{let b;b=new Eh;b.dt=a;return b;},C$=(a,b)=>{let c;c=Eo(a,b);if(c===null)return null;return c.cc;},Eo=(a,b)=>{let c,d;if(b===null)c=EN(a);else{d=b.N();c=Ef(a,b,d&(a.bO.data.length-1|0),d);}return c;},Ef
=(a,b,c,d)=>{let e;e=a.bO.data[c];while(e!==null&&!(e.cv==d&&ET(b,e.b9))){e=e.bU;}return e;},EN=a=>{let b;b=a.bO.data[0];while(b!==null&&b.b9!==null){b=b.bU;}return b;},GT=a=>{let b;if(a.ci===null){b=new EF;b.cs=a;a.ci=b;}return a.ci;},El=(a,b,c)=>{let d,e,f;if(b===null){d=EN(a);if(d===null){a.bW=a.bW+1|0;d=D3(a,null,0,0);e=a.bV+1|0;a.bV=e;if(e>a.cD)Ew(a);}}else{e=b.N();f=e&(a.bO.data.length-1|0);d=Ef(a,b,f,e);if(d===null){a.bW=a.bW+1|0;d=D3(a,b,f,e);e=a.bV+1|0;a.bV=e;if(e>a.cD)Ew(a);}}b=d.cc;d.cc=c;return b;},D3
=(a,b,c,d)=>{let e,f,g;e=new B7;f=null;e.b9=b;e.cc=f;e.cv=d;g=a.bO.data;e.bU=g[c];g[c]=e;return e;},Ew=a=>{let b,c,d,e,f,g,h,i;b=a.bO.data.length;b=DC(!b?1:b<<1);c=L(B7,b);d=c.data;e=0;f=b-1|0;while(true){g=a.bO.data;if(e>=g.length)break;h=g[e];g[e]=null;while(h!==null){b=h.cv&f;i=h.bU;h.bU=d[b];d[b]=h;h=i;}e=e+1|0;}a.bO=c;Eg(a);},DS=(a,b)=>{let c,d,e,f,g,h;a:{c=0;d=null;if(b===null){e=a.bO.data[0];while(e!==null){if(e.b9===null)break a;b=e.bU;d=e;e=b;}}else{f=DL(b);g=a.bO.data;c=f&(g.length-1|0);e=g[c];while
(e!==null&&!(e.cv==f&&ET(b,e.b9))){h=e.bU;d=e;e=h;}}}if(e===null)e=null;else{if(d!==null)d.bU=e.bU;else a.bO.data[c]=e.bU;a.bW=a.bW+1|0;a.bV=a.bV-1|0;}if(e===null)return null;return e.cc;},GI=a=>{return a.bV;},ET=(b,c)=>{return b!==c&&!b.L(c)?0:1;},D$=E(0),BW=E(0),BD=E(),Co=a=>{return a.b7?0:1;},FS=(a,b)=>{let c,d;c=a.C();while(c.D()){d=c.E();if(d===b?1:d!==null?d.L(b):b!==null?0:1)return 1;}return 0;},Ex=E(0),DQ=E(0);
function BF(){BD.call(this);this.cr=0;}
let O=a=>{let b;b=new EI;b.c8=a;b.dF=a.cr;b.cO=a.b7;b.dg=(-1);return b;},Cn=E(0);
function BV(){let a=this;BF.call(a);a.b8=null;a.b7=0;}
let Gw=a=>{Cr(a,10);},Dd=()=>{let a=new BV();Gw(a);return a;},Cr=(a,b)=>{let c;if(b>=0){a.b8=L(D,b);return;}c=new Bw;K(c);I(c);},Hy=a=>{let b=new BV();Cr(b,a);return b;},Dc=(a,b)=>{let c,d,e,f,g,h;c=a.b7+1|0;d=a.b8.data.length;if(d<c){c=d>=1073741823?2147483647:B3(c,B3(d*2|0,5));e=a.b8;f=Cq(Bo(e));if(f===null){b=new B1;K(b);I(b);}if(f===F(Ff)){b=new Bw;K(b);I(b);}if(c<0){b=new EZ;K(b);I(b);}g=e.data;e=Fy(f.b3,c);h=Ev(c,g.length);d=0;while(d<h){e.data[d]=g[d];d=d+1|0;}a.b8=e;}e=a.b8.data;h=a.b7;a.b7=h+1|0;e[h]
=b;a.cr=a.cr+1|0;return 1;},Bw=E(J);
function C1(){D.call(this);this.cn=Bs;}
let G0=(a,b)=>{if(a===b)return 1;if(!(b instanceof C1))return 0;return FO(a.cn,b.cn)?0:1;},DL=a=>{let b;b=a.cn;return Dv(b)^E6(b);},Dn=E(0);
function CF(){let a=this;D.call(a);a.b9=null;a.cc=null;}
function B7(){let a=this;CF.call(a);a.cv=0;a.bU=null;}
let EX=E(0);
function DW(){let a=this;D.call(a);a.dJ=Bs;a.dH=Bs;a.dI=null;a.c0=null;a.dK=null;a.dM=0;a.dQ=null;}
let GZ=null,T=null,Cy=0,Fc=0,F1=null,BM=b=>{if(T!==b)T=b;T.dH=Fn();},E8=()=>{return T;},Fa=b=>{let $p,$z;$p=0;if(C_()){let $T=Bg();$p=$T.l();b=$T.l();}_:while(true){switch($p){case 0:$p=1;case 1:GV(b);if(CI()){break _;}return;default:Ct();}}Bg().s(b,$p);},Fb=(b,c)=>{let d,e;d=T;e=new DB;e.dD=d;e.de=c;e.dN=DH(e,E_(b,Ch(2147483647))?2147483647:Dv(b));d.c0=e;},E7=()=>{let b,c,d;b=new DW;c=null;b.dI=new D;b.dM=1;b.dK=G(27);b.dQ=c;d=Cy;Cy=d+1|0;b.dJ=Ch(d);GZ=b;T=b;Cy=1;Fc=1;F1=new EG;},GV=b=>{let thread=Dh();let javaThread
=Dx();if(thread.isResuming()){thread.status=0;let result=thread.attribute;if(result instanceof Error){throw result;}return result;}let callback=function(){};callback.g=val=>{thread.attribute=val;BY(javaThread);thread.resume();};callback.bH=e=>{thread.attribute=CE(e);BY(javaThread);thread.resume();};callback=EU(callback);thread.suspend(()=>{try {Fb(b,callback);;}catch($e){callback.bH($e);}});return null;};
function Ez(){let a=this;D.call(a);a.b4=null;a.dS=null;a.bP=null;a.bS=0;}
let Ej=E(J),C2=E(J),Gh=E(),B2=b=>{return b.length?0:1;},B9=E(0);
function Ek(){D.call(this);this.cT=null;}
let G4=a=>{let b,c,d,e;b=a.cT;if(!BT(b)){c=b.bR;if(c.bP===null){b=c.b4;if(b!==null&&!B2(b)){b=c.b4.shift();if(b!==null&&!(b instanceof Bj()))b=Fd(b);d=b;c.b4=null;b=d;c=b.cX;d=b.cZ;e=b.cV;b=b.cW;BM(c);d=d.bR;d.bP=c;d.bS=d.bS+e|0;c=null;BS(b,c);}}}},Em=E(0),EG=E(),Fv=E(),Hz=(b,c,d,e,f)=>{if(c>=0&&e>=0&&f>=0&&(c+f|0)<=B6(b)&&(e+f|0)<=B6(d)){B_(b,c,d,e,f);return;}b=new Bl;K(b);I(b);},B_=(b,c,d,e,f)=>{if(f!==0){if(typeof b.data.buffer!=='undefined'){d.data.set(b.data.subarray(c,c+f),e);}else if(b!==d||e<c){for(let i
=0;i<f;i=i+1|0){d.data[e++]=b.data[c++];}}else {c=c+f|0;e=e+f|0;for(let i=0;i<f;i=i+1|0){d.data[ --e]=b.data[ --c];}}}},Fn=()=>{return Dg((new Date()).getTime());},CG=()=>{return Dg(performance.now()*1000000.0);},DP=E(0);
function Dq(){D.call(this);this.cH=null;}
let EU=b=>{let c;c=new Dq;c.cH=b;return c;},BS=(a,b)=>{a.cH.g(b);},Gg=(a,b)=>{a.cH.bH(b);};
function DU(){let a=this;D.call(a);a.cX=null;a.cZ=null;a.cV=0;a.cW=null;}
let Ca=E(BN),Bi=E(0);
function BA(){D.call(this);this.b_=0;}
function Bt(){let a=this;D.call(a);a.cL=0.0;a.cE=0.0;}
let BG=E(),B0=E(),B4=E(),Ho=E(),Br=E(0);
function EI(){let a=this;D.call(a);a.cM=0;a.dF=0;a.cO=0;a.dg=0;a.c8=null;}
let Q=a=>{return a.cM>=a.cO?0:1;},S=a=>{let b,c,d;b=a.dF;c=a.c8;if(b<c.cr){c=new CS;K(c);I(c);}d=a.cM;a.dg=d;a.cM=d+1|0;c=c;if(d>=0&&d<c.b7)return c.b8.data[d];c=new Bl;K(c);I(c);},DT=E(0),Er=E(0);
function DB(){let a=this;D.call(a);a.dD=null;a.de=null;a.dR=0;a.dN=0;}
let Gj=a=>{let b,c;if(!a.dR){b=a.dD;b.c0=null;BM(b);c=a.de;b=null;BS(c,b);}},Hm=E(),EY=E(),FL=null,Dr=null,Cd=null,BX=null,Eb=null,Do=null,Dz=null,BI=()=>{BI=Et(EY);Fp();},Fp=()=>{let b;FL=new WeakMap();Dr=!(typeof WeakRef!=='undefined'?1:0)?null:new WeakMap();Cd=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();BX=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();if(Cd===null)b=null;else{b=new Cw;b=new FinalizationRegistry(M(R(b),"accept"));}Do=b;if(BX===null)b=null;else{b=new Cv;b=new FinalizationRegistry(M(R(b),
"accept"));}Dz=b;},FN=E(),GF=E(),C3=E(0),Cw=E(),Hc=(b,c)=>{b;BI();Cd.delete(c);},Cv=E(),Ge=(b,c)=>{b;BI();BX.delete(c);},CA=E(0),D5=E(),GR=(a,b)=>{return Da();},Fs=E(),GL=()=>{return Math.random();},Ev=(b,c)=>{if(b<c)c=b;return c;},B3=(b,c)=>{if(b>c)c=b;return c;},CS=E(J),Fh=E(),EL=null,Bx=null,Fj=null,Df=null,FZ=null,FU=null,Gc=()=>{EL=new Dm;Bx=new Dk;Fj=new Dl;Df=new Di;FZ=new Dj;FU=new EK;},Gz=E(),B6=b=>{if(b===null||b.constructor.$meta.item==='undefined'){I(Hu());}return b.data.length;},Fy=(b,c)=>{if(b.$meta.primitive)
{switch(b){};}return L(b,c);},B1=E(J),EZ=E(J),Ep=E(0),Bh=E(BD),CR=E(Bh),Dm=E(CR),Fm=a=>{return Df;},CB=E(BO),Dk=E(CB),FY=a=>{return EL;},FC=a=>{return 0;},E4=(a,b)=>{return null;};
let C9=E(BF),Dl=E(C9),Di=E(),Gd=a=>{return 0;},Fo=a=>{let b;b=new C7;K(b);I(b);},EV=E(0),Dj=E(),EK=E(),Cz=E(Bl),Gi=a=>{K(a);},GB=()=>{let a=new Cz();Gi(a);return a;};
function Bc(){let a=this;D.call(a);a.cf=0;a.ce=0;}
function Ba(){D.call(this);this.b5=null;}
function B8(){D.call(this);this.c5=null;}
let D2=E(0),CQ=E(),EQ=(a,b)=>{let c;if(b<=0){c=new Bw;K(c);I(c);}return GL()*b|0;},EM=E(CQ),Db=null,Fi=()=>{Db=new EM;};
function Ec(){Bh.call(this);this.cB=null;}
let FB=a=>{let b,c;b=(a.cB.bn()).C();c=new ER;c.dL=a;c.cF=b;return c;},F_=a=>{return a.cB.bh();},Cg=E(J);
function ER(){let a=this;D.call(a);a.cF=null;a.dL=null;}
let Gs=a=>{return a.cF.D();},Gu=a=>{return (a.cF.E()).b9;};
function EF(){Bh.call(this);this.cs=null;}
let Hg=(a,b)=>{return E0(a.cs,b);},Gk=a=>{return a.cs.bV;},E5=a=>{let b;b=new DM;Cl(b,a.cs);return b;},GW=E(BR),GC=null,Hb=()=>{GC=F(F5);},Dt=E(),E3=(a,b)=>{return Da();};
function BB(){let a=this;D.call(a);a.cu=0;a.dE=0;a.cl=null;a.cj=null;a.dB=null;a.cq=null;}
let Cl=(a,b)=>{a.cq=b;a.dE=b.bW;a.cl=null;},Hq=a=>{let b=new BB();Cl(b,a);return b;},CP=a=>{let b,c;if(a.cl!==null)return 1;while(true){b=a.cu;c=a.cq.bO.data;if(b>=c.length)break;if(c[b]!==null)return 1;a.cu=b+1|0;}return 0;},DK=a=>{let b,c,d,e;if(a.dE!=a.cq.bW){b=new CS;K(b);I(b);}if(!CP(a)){b=new C7;K(b);I(b);}b=a.cl;if(b!==null){c=a.cj;if(c!==null)a.dB=c;a.cj=b;a.cl=b.bU;}else{d=a.cq.bO.data;e=a.cu;a.cu=e+1|0;b=d[e];a.cj=b;a.cl=b.bU;a.dB=null;}},DM=E(BB),GD=a=>{DK(a);return a.cj.b9;};
function Eh(){Bh.call(this);this.dt=null;}
let Du=a=>{let b;b=new D1;Cl(b,a.dt);return b;},D1=E(BB),DZ=a=>{DK(a);return a.cj;},C7=E(J);
Gl([-1,"java",0,"util",-1,"kfs",2,"ecs",3,"tetris",4,"comp",3,"base",6,"comp"]);
Cp([D,0,0,[],0,3,0,0,["N",H(G6),"L",Be(FD)],D9,0,D,[],3,3,0,0,0,Dw,0,D,[],3,3,0,0,0,Es,0,D,[D9,Dw],4,3,0,0,0,GM,0,D,[],4,3,0,0,0,F6,0,D,[],4,3,0,0,0,CH,0,D,[],0,3,0,0,0,BN,0,CH,[],0,3,0,0,0,J,0,BN,[],0,3,0,0,0,D7,0,J,[],0,3,0,0,0,Bq,0,D,[],3,3,0,0,0,BJ,0,D,[],3,3,0,0,0,Cs,0,D,[],3,3,0,0,0,Bd,0,D,[Bq,BJ,Cs],0,3,0,0,0,BR,0,D,[Bq],1,3,0,0,0,FR,0,BR,[BJ],0,3,0,0,0,C6,0,D,[Bq,Cs],0,0,0,0,0,E1,0,D,[],3,3,0,0,0,DJ,0,C6,[E1],0,3,0,0,0,GJ,0,D,[],0,3,0,0,0,G2,0,D,[],0,3,0,0,0,FK,0,D,[],0,3,0,0,0,CD,0,D,[],0,3,0,Cc,0,Hh,
0,D,[],4,3,0,0,0,Cx,0,D,[],3,3,0,0,0,Ee,0,D,[Cx],0,3,0,0,0,DY,0,D,[BJ],0,3,0,0,0,Bu,0,D,[],3,3,0,0,0,U,0,D,[Bu],3,3,0,0,0,CY,0,D,[U],0,0,0,0,0,C5,0,D,[],4,3,0,0,0,CZ,0,D,[U],0,0,0,0,0,C0,0,D,[U],0,0,0,0,0,CT,0,D,[U],0,0,0,0,0,CU,0,D,[U],0,0,0,0,0,CV,0,D,[U],0,0,0,0,0,CW,0,D,[U],0,0,0,0,0,CN,0,D,[U],0,0,0,0,0,CO,0,D,[U],0,0,0,0,0,CJ,0,D,[U],0,0,0,0,0,CL,0,D,[U],0,0,0,0,0,CM,0,D,[U],0,0,0,0,0,CK,0,D,[U],0,0,0,0,0,D0,0,D,[],0,3,0,0,0,Bk,0,D,[],3,3,0,0,0,CC,0,D,[Bk],0,3,0,0,["F",H(FE)],DF,0,D,[],0,3,0,0,0,Go,0,
D,[],4,3,0,0,0,D_,0,D,[Bk],0,3,0,0,["F",H(Gx)],EE,0,D,[Bk],0,3,0,0,["F",H(Fz)]]);
Cp([DG,0,D,[Bk],0,3,0,0,["F",H(GQ)],BH,0,D,[Bk],0,3,0,0,["F",H(He)],D4,0,D,[Bk],0,3,0,0,["F",H(Gn)],Ed,0,D,[Bk],0,3,0,0,["F",H(Gy)],Ci,0,D,[U],0,0,0,0,0,Bl,0,J,[],0,3,0,0,0,DR,0,D,[],3,3,0,0,0,BO,0,D,[DR],1,3,0,0,["bf",H(GO)],Cf,0,D,[],3,3,0,0,0,D8,"HashMap",1,BO,[Cf,Bq],0,3,0,0,["bn",H(EB),"bc",Be(C$),"bf",H(GT),"bh",H(GI)],D$,0,D,[],3,3,0,0,0,BW,0,D,[D$],3,3,0,0,0,BD,0,D,[BW],1,3,0,0,["bi",Be(FS)],Ex,0,D,[BW],3,3,0,0,0,DQ,0,D,[Ex],3,3,0,0,0,BF,0,BD,[DQ],1,3,0,0,0,Cn,0,D,[],3,3,0,0,0,BV,0,BF,[Cf,Bq,Cn],0,3,
0,0,0,Bw,0,J,[],0,3,0,0,0,C1,0,D,[],0,3,0,0,["L",Be(G0),"N",H(DL)],Dn,0,D,[],3,3,0,0,0,CF,0,D,[Dn,Cf],0,0,0,0,0,B7,0,CF,[],0,0,0,0,0,EX,0,D,[],3,3,0,0,0,DW,0,D,[EX],0,3,0,0,0,Ez,0,D,[],0,0,0,0,0,Ej,0,J,[],0,3,0,0,0,C2,0,J,[],0,3,0,0,0,Gh,0,D,[Bu],1,3,0,0,0,B9,0,D,[],3,3,0,0,0,Ek,0,D,[B9],0,3,0,0,["q",H(G4)],Em,0,D,[],3,3,0,0,0,EG,0,D,[Em],0,3,0,0,0,Fv,0,D,[],4,3,0,0,0,DP,0,D,[],3,3,0,0,0,Dq,0,D,[DP],0,0,0,0,["g",Be(BS),"bH",Be(Gg)],DU,0,D,[B9],0,3,0,0,0,Ca,0,BN,[],0,3,0,0,0,Bi,0,D,[],3,3,0,0,0,BA,"MovementIntX",
5,D,[Bi],0,3,0,0,0,Bt,"Gravity",5,D,[Bi],0,3,0,0,0,BG,"Active",7,D,[Bi],0,3,0,0,0,B0,"Rotate",5,D,[Bi],0,3,0,0,0,B4,"GameOver",7,D,[Bi],0,3,0,0,0,Ho,0,D,[],0,3,0,0,0,Br,0,D,[],3,3,0,0,0,EI,0,D,[Br],0,0,0,0,0,DT,0,D,[],3,3,0,0,0,Er,0,D,[],3,3,0,0,0,DB,0,D,[B9,DT,Er],0,0,0,0,["q",H(Gj)]]);
Cp([Hm,0,D,[],4,3,0,0,0,EY,0,D,[],0,0,0,BI,0,FN,0,D,[Bu],0,3,0,0,0,GF,0,D,[Bu],1,3,0,0,0,C3,0,D,[Bu],3,0,0,0,0,Cw,0,D,[C3],0,3,0,0,0,Cv,0,D,[C3],0,3,0,0,0,CA,0,D,[],3,3,0,0,0,D5,0,D,[CA],0,3,0,0,["bu",Be(GR)],Fs,0,D,[],4,3,0,0,0,CS,0,J,[],0,3,0,0,0,Fh,0,D,[],0,3,0,0,0,Gz,0,D,[],4,3,0,0,0,B1,0,J,[],0,3,0,0,0,EZ,0,J,[],0,3,0,0,0,Ep,0,D,[BW],3,3,0,0,0,Bh,0,BD,[Ep],1,3,0,0,0,CR,0,Bh,[],1,0,0,0,0,Dm,0,CR,[],0,0,0,0,["C",H(Fm)],CB,0,BO,[],1,0,0,0,0,Dk,0,CB,[],0,0,0,0,["bn",H(FY),"bh",H(FC),"bc",Be(E4)],C9,0,BF,[Cn],
1,0,0,0,0,Dl,0,C9,[],0,0,0,0,0,Di,0,D,[Br],0,0,0,0,["D",H(Gd),"E",H(Fo)],EV,0,D,[Br],3,3,0,0,0,Dj,0,D,[EV],0,0,0,0,0,EK,0,D,[Cx],0,3,0,0,0,Cz,0,Bl,[],0,3,0,0,0,Bc,"PositionInt",7,D,[Bi],0,3,0,0,0,Ba,"ShapeInt",5,D,[Bi],0,3,0,0,0,B8,"Color",7,D,[Bi],0,3,0,0,0,D2,0,D,[],3,3,0,0,0,CQ,0,D,[D2,Bq],0,3,0,0,0,EM,0,CQ,[],0,3,0,0,0,Ec,0,Bh,[],0,0,0,0,["C",H(FB),"bh",H(F_)],Cg,0,J,[],0,3,0,0,0,ER,0,D,[Br],0,0,0,0,["D",H(Gs),"E",H(Gu)],EF,0,Bh,[],0,0,0,0,["bi",Be(Hg),"bh",H(Gk),"C",H(E5)],GW,0,BR,[BJ],0,3,0,0,0,Dt,0,D,
[CA],0,3,0,0,["bu",Be(E3)],BB,0,D,[],0,0,0,0,["D",H(CP)],DM,0,BB,[Br],0,0,0,0,["E",H(GD)],Eh,0,Bh,[],0,0,0,0,["C",H(Du)],D1,0,BB,[Br],0,0,0,0,["E",H(DZ)],C7,0,J,[],0,3,0,0,0]);
let F3=N(De),DX=N(Bb);
FV(["Can\'t enter monitor from another thread synchronously","0","<java_object>@","null","object","function","string","number","undefined","DownArrow","LeftArrow","i","j","k","l","RightArrow","ArrowUp","cyan","orange","yellow","green","blue","magenta","red"," is not subtype of ","Either src or dest is null","","main"]);
Bd.prototype.toString=function(){return CX(this);};
Bd.prototype.valueOf=Bd.prototype.toString;D.prototype.toString=function(){return CX(F8(this));};
D.prototype.__teavm_class__=function(){return G8(this);};
let C=E$(Fu);
C.javaException=Fg;
let HA=Symbol('jsoClass');
(()=>{let c;c=CY.prototype;c.handleEvent=P(GY);c=CZ.prototype;c.handleEvent=P(Gr);c=C0.prototype;c.handleEvent=P(FT);c=CT.prototype;c.handleEvent=P(Hk);c=CU.prototype;c.handleEvent=P(F2);c=CV.prototype;c.handleEvent=P(GE);c=CW.prototype;c.handleEvent=P(GG);c=CN.prototype;c.handleEvent=P(F9);c=CO.prototype;c.handleEvent=P(Hf);c=CJ.prototype;c.handleEvent=P(E9);c=CL.prototype;c.handleEvent=P(FF);c=CM.prototype;c.handleEvent=P(Gm);c=CK.prototype;c.handleEvent=P(G7);c=Ci.prototype;c.handleEvent=P(GS);c=Cw.prototype;c.accept
=P(Hc);c=Cv.prototype;c.accept=P(Ge);})();
B.main=C;}));
